//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppArmonii.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenerosMusicos
    {
        public int id { get; set; }
        public Nullable<int> idGenero { get; set; }
        public Nullable<int> idMusico { get; set; }
    
        public virtual Generos Generos { get; set; }
        public virtual Musico Musico { get; set; }
    }
}
