//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppArmonii.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje
    {
        public int id { get; set; }
        public Nullable<int> idUsuarioLocal { get; set; }
        public Nullable<int> idUsuarioMusico { get; set; }
        public Nullable<System.DateTime> fechaEnvio { get; set; }
        public string mensaje1 { get; set; }
        public string emisor { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
