//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppArmonii.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musico()
        {
            this.Evento = new HashSet<Evento>();
            this.Valoracion = new HashSet<Valoracion>();
        }
    
        public int id { get; set; }
        public string genero { get; set; }
        public string biografia { get; set; }
        public Nullable<int> edad { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string apodo { get; set; }
        public string apellido { get; set; }
        public string generoMusical { get; set; }
        public string imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evento> Evento { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valoracion> Valoracion { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
