//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppArmonii.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valoracion
    {
        public int id { get; set; }
        public Nullable<int> puntuacion { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idEvento { get; set; }
        public Nullable<int> idLocal { get; set; }
        public Nullable<int> idMusico { get; set; }
        public string emisor { get; set; }
    
        public virtual Evento Evento { get; set; }
        public virtual Local Local { get; set; }
        public virtual Musico Musico { get; set; }
    }
}
